import axios from "axios";
import Head from "next/head";
import Bibliotheque from "../src/components/Display/Bibliotheque";
import Authors from "../src/components/Display/Authors";
import { useQuery } from "react-query";
import Genre from "../src/components/Display/Genre";

import Add from "../src/components/forms/Add";

// Get books, authors & genres
const getAllBooks = async () => {
  try {
    const allBooks = await axios.get("http://localhost:5000/api/v1/books");
    return allBooks.data;
  } catch (error) {
    console.log(error);
  }
};

const getAllAuthors = async () => {
  try {
    const allAuthors = await axios.get("http://localhost:5000/api/v1/authors");
    return allAuthors.data;
  } catch (error) {
    console.log(error);
  }
};

const getAllGenres = async () => {
  try {
    const allGenres = await axios.get("http://localhost:5000/api/v1/genres");
    return allGenres.data;
  } catch (error) {
    console.log(error);
  }
};

export default function Home() {
  // UseQuery
  const { isLoading, data: allBooks, error } = useQuery("books", getAllBooks);
  const { data: allAuthors, isLoading: authorLoading } = useQuery(
    "authors",
    getAllAuthors
  );
  const { data: allGenres, isLoading: genreLoading } = useQuery(
    "genres",
    getAllGenres
  );

  if (isLoading || authorLoading || genreLoading) {
    return <p>Loading...</p>;
  }

  if (error) {
    return <p>Something bad happen</p>;
  }

  // Register form state

  return (
    <div>
      <Head>
        <title>Wild Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <div className="bg-background py-16 ">
          <p className=" text-white w-2/3 m-auto py-10 text-center ">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Commodi
            deleniti nemo eius corrupti molestias reiciendis sint impedit animi
            itaque, autem neque et accusantium praesentium, velit quis
            laboriosam asperiores culpa exercitationem? Lorem ipsum dolor, sit
            amet consectetur adipisicing elit. Commodi deleniti nemo eius
            corrupti molestias reiciendis sint impedit animi itaque, autem neque
            et accusantium praesentium, velit quis laboriosam asperiores culpa
            exercitationem?
          </p>
        </div>
        <div className=" py-10 w-full flex flex-col items-center bg-slate-300 ">
          <Bibliotheque
            allBooks={allBooks}
            allAuthors={allAuthors}
            allGenres={allGenres}
          />
          <Authors allAuthors={allAuthors} />
          <Genre allGenres={allGenres} />
          <Add allAuthors={allAuthors} allGenres={allGenres} />
        </div>
      </main>
    </div>
  );
}
